# Tymczasowy nginx do uzyskania certyfikatu SSL
server {
    listen 80;
    server_name rezerwuj.kzelman.pl;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 "Initializing...";
    }
}
